/*           ESTRUTURA DE CONTROLE DE REPETIÇÃO

=> EXISTEM TRÊS ESTRUTURA DE REPETIÇÃO:ENQUANTO;REPITA; PARAR

=> EM MUITOS CASOS É NECESSÁRIO REPETIR UM TRECHO DE UM PROGRAMA DIVERSAS VEZES. NESSE CASO
PODEMOS USAR UM "LOOP" QUE EFETUE ESSA REPETIÇÃO DE CÓDIGO QUANTAS VEZES FOREM NECESSÁRIAS.

=> OS LOOPS SÃO CHAMADOS TAMBÉM DE LAÇO DE REPETIÇÃO.

=> ESSA ESTRUTURA REALIZA UM TESTE LÓGICO NO INICIO DO LOOP, E CADA VEZ QUE O TESTE RETORNA O VALOR
VERDADEIRO, OS COMANDOS ASSOCIADOS AO LAÇO SÃO EXECUTADOS.

=> QUANDO O TESTE RETORNAR FALSO, O LAÇO É ENCERRADO E O PROCESSAMENTO VOLTA PARA O FLUXO PRINCIPAL DO
PROGRAMA


=> REPETIÇÃO COM VARIAVEL  DE CONTROLE 

    ESTRUTURA DE REPETIÇÃO for(estrutura parar ou um whlile simplificado)


>>> PERMITE CONSTRUIR ESTRUTURAS DE LOOP PARA CASOS ONDE SE CONHECE DE ANTEMÃO O NÚMERO DE REPETIÇÕES
QUE DEVEM SER REALIZADAS(NÚMERO FINITO DE LACOS)

>>> POR EXEMPLO, SE SOUBERMOS DE ANTEMÃO QUE O LAÇO DEVE REPETIR 10 VEZES, PODEMOS USAR A ESTRUTURA for.



          SINTAXE DE for EM C


 for(variavel = inicio; fim;incremento){
     instruções

 }

>>>>>>>> for(variavel = inicio; inicio <= x;inicio++)


.*/

int numero = 10;


for(int inicio = 1; inicio<= 10; inicio++){

    Console.WriteLine($"{numero} X {inicio} = {numero * inicio}");

}
